name: github pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install Poetry
        run: |
          python3 -m pip install poetry

      - name: Install dependencies
        run: poetry install

      - run: poetry run mkdocs build

      - run: echo "dispike.ms7m.me" >> ./site/CNAME
      - run: echo "Documentation was automatically built on $(date). Do **not edit directly**." >> ./site/README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
