# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Dispike

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Poetry
        run: |
          pip install poetry
          poetry install
      - name: Lint with pylint
        run: |
          # stop the build if there are Python syntax errors or undefined names
          # Bug with pylint and pydantic
          # https://github.com/samuelcolvin/pydantic/issues/1961
          poetry run pylint --errors-only --extension-pkg-whitelist='pydantic' dispike
      - name: Test with pytest
        run: |
          poetry run pytest
